### PR TITLE
Use negative lookbehind instead

### PR DESCRIPTION
**Pull request by priyaselvaganesan**

### CODE REVIEW

**Comment by priyaselvaganesan** [comment]
@iplay88keys, This regex seems to work for the QueryChecks issue we identified in [K8SSAAS-1417](https://jira.eng.vmware.com/browse/K8SSAAS-1417). I feel like I am missing something and it can't be that simple. Can you thing of any corner cases that I might have missed?

**Review by iplay88keys — APPROVED** [review]

**Comment by johncornish** [comment]
Is this truly ready to merge or is this part of ongoing story [K8SSAAS-1181](https://jira.eng.vmware.com/browse/K8SSAAS-1181)? I hesitated to merge

**Comment by priyaselvaganesan** [comment]
> 


I just tried the dashboard_validator with the changes in it and it looks to be having compilation issues. I will change this to a WIP PR. Thank you for hesitating!!
> Is this truly ready to merge or is this part of ongoing story [K8SSAAS-1181](https://jira.eng.vmware.com/browse/K8SSAAS-1181)? I hesitated to merge

**Comment by iplay88keys** [comment]
@priyaselvaganesan I've fixed the compilation error. Not sure how I missed that previously.

**Review by johncornish — APPROVED** [review]

**Pull request merged**
